CREATE TABLE IF NOT EXISTS Author (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    author_id BIGINT
);

CREATE TABLE IF NOT EXISTS Contact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    mobile VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    author_id BIGINT
 );